### PR TITLE
Config

### PR DESCRIPTION
**Pull request by mikespub**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-cops/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Add $config['cops_kepubify_path'] in root/defaults/config_local.php

## Benefits of this PR and context:

Default configuration of kepubify path in line with previous Dockerfile change

## How Has This Been Tested?

Create docker image and run

## Source / References:

https://github.com/mikespub-org/seblucas-cops/issues/77

### CODE REVIEW

**Comment by mikespub** [comment]
Hi @aptalca & friends

I've updated this PR to include the config changes needed for COPS 3.x. Any chance this could be reviewed?

Thanks :-)
P.S.: if you have some good guidelines on how to adapt the nginx default.conf.sample file to make use of a front controller and get rid of index.php/ in URLs, I'd be happy to test it for COPS and submit another PR later

**Comment by aptalca** [comment]
Thanks @mikespub 

I did a quick review and it looks good.

But I'm also thinking we should do the migration of the config file automatically for existing users.

If you're planning on releasing v3 soon, we can temporarily pause our external checks, update this PR with the migration and after you release v3 we merge this PR and reenable external checks. Does that work?

**Comment by aptalca** [comment]
On second thought, we could probably do the migration conditionally so we don't have to coordinate releases

**Comment by aptalca** [comment]
Opened a PR https://github.com/mikespub-org/docker-cops/pull/1

**Comment by aptalca** [comment]
I just noticed your release candidate is marked as `latest` in github releases so it's already building 3.1.1
And it looks like we already pushed a broken release as a result. Oops

The webpage seems to error out on a fresh container as seen in the test result above: https://ci-tests.linuxserver.io/lspipepr/cops/3.1.1-pkg-d408948f-dev-e7061aed628b200b22f9c3e4344eb1bff06491d1-pr-57/index.html

**Comment by mikespub** [comment]
Actually COPS is now sending you to index.php/check instead of checkconfig.php - which is the output you see there. The docker part is fine, but the COPS part is not (quite) yet.

That's why I called this a release candidate rather than a release, to iron out these little issues. Once this docker-cops PR is merged and working, I can prepare a next release with bug fixes on the COPS side and it'll automatically go through the next time. But for that I needed the config file issue resolved first :-)

**Comment by mikespub** [comment]
Thanks @aptalca - always a pleasure working with the linuxserver team...
You do great work, and we appreciate it even if we don't say it enough :-)

**Comment by aptalca** [comment]
You guys are doing the actual work, we just try to keep up 😅

**Pull request merged**
