### PR TITLE
FIX: update rewrite rules

### LINKED ISSUE #31: Include URL rewriting support in nginx config
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

## Expected Behavior

When editing config_local.php to enable url writing, it should not generate a 404 error when attempting to download.
`    $config['cops_use_url_rewriting'] = "1";`

NGINX config is listed here
https://github.com/seblucas/cops/wiki/Url-Rewriting-with-COPS

## Current Behavior

404 error is generated for all /download or /view urls

## Steps to Reproduce

1. edit config_local.php to include `    $config['cops_use_url_rewriting'] = "1";`
2. navigate to book using COPS server.
3. Click download, or folder buttons
4. get 404 error

## Environment
**OS:** Armbian
**CPU architecture:** arm64
**How docker service was installed:** from the distro repo, using armbian-setup

## Command used to create docker container (run/create/compose/screenshot)

```
  cops:
    image: linuxserver/cops
    container_name: cops
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=100
    volumes:
      - /opt/appdata/cops:/config
      - /mnt/storage/media/Books:/books
    ports:
      - 9090:80
    restart: unless-stopped
```

### PR DESCRIPTION
**Pull request by NgrNxk**
As the root is set to `/var/www/localhost/cops`, the location for rewriting should not include "/cops/" as this will never be met. We need just "/" here.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-cops/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Benefits of this PR and context:

Without URL rewriting, FBReader and Librera Reader Android apps do not work correctly with COPS.

- FBReader can't open the files because the extension is missing on the downloaded file
- Librera Reader can display the file but the filename is something like `fetch.php?data=...`

When setting `cops_use_url_rewriting`, I get 404 without this patch.

## How Has This Been Tested?

After changing  `cops_use_url_rewriting` in my `config_local.php` with this patch included, both applications worked correctly:

- FBReader opens downloaded files
- Librera Reader displays the correct file names

I tested it with CBR and CBZ files.
## Source / References:

Now that I see it, it could be that this fixes #31.

### CODE REVIEW

**Comment by NgrNxk** [comment]
So, how can I push it further?

**Comment by aptalca** [comment]
This change does not affect regular web connections to cops as those are handled by line 30, the php location block.

That block you're referring to is for the kobo reader.

*Unless I misunderstood your intentions (op was fairly thin on details)

**Comment by NgrNxk** [comment]
I will amend the PR. But the code isn't just for "kobo reader": this comment is wrong. I can see the error in Librera Reader (files are named `fetch.php?data=...`) and FBReader (not able to open the downloaded files because of missing extension).

**Comment by seblucas** [comment]
If I may add my opinion. I think this PR should be merged : @NgrNxk  explained the problem perfectly.

**Comment by nemchik** [comment]
https://github.com/linuxserver/docker-cops/pull/34 has merged and is a significant change to the config and the install location of cops inside the image. I'm going to close this PR for now, but if the new config would still benefit from these changes I welcome you to reopen this PR and rebase your changes.

**Pull request closed without merging**
